In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("placements dataset.csv")
print(df)

      Student ID          Name  Gender  Year  \
0              1  Aryan Ghosal    Male  2023
1              2  Kunal Pillai    Male  2023
2              3     Dev Gupta    Male  2023
3              4  Manish Yadav    Male  2023
4              5    Isha Singh  Female  2023
...          ...           ...     ...   ...
9995        9996     Rani Jain  Female  2022
9996        9997   Aditya Jain    Male  2025
9997        9998    Diya Kumar  Female  2023
9998        9999  Shreya Verma  Female  2024
9999       10000  Zara Prakash  Female  2023

                                                 Skills  Backlogs  \
0                  Digital Marketing, ML/AI, Blockchain         1
1                        Blockchain, Python, Networking         0
2                                                   C++         1
3                                    DevOps, Networking         1
4                   Web Dev (Full Stack), ML/AI, DevOps         0
...                                                 ...       ...
9995                   Digital Marketing, Cybersecurity         1
9996                Web Dev (Full Stack), Cybersecurity         1
9997               Cybersecurity, Cloud (AWS/Azure/GCP)         2
9998  Cybersecurity, C++, Digital Marketing, Web Dev...         1
9999  Digital Marketing, Cloud (AWS/Azure/GCP), Netw...         0

      Projects Completed  Internships Companies Placed Company Type  \
0                      6            2              TCS  Established
1                     10            2             Meta  Established
2                      5            0              NaN          NaN
3                      8            4           Zomato      Startup
4                      8            3      Tata Motors  Established
...                  ...          ...              ...          ...
9995                   7            2            Wipro  Established
9996                   2            3           Amazon  Established
9997                   3            2          Infosys  Established
9998                   8            4        Cognizant  Established
9999                   3            2              NaN          NaN

           Domain   Salary Higher Studies Higher Studies Field   Location
0      Automotive  2271743             No                  NaN  Ahmedabad
1      E-commerce  1386191             No                  NaN      Delhi
2             NaN        0             No                  NaN    Kolkata
3         FinTech  1011924             No                  NaN    Chennai
4     IT Services  1017889             No                  NaN  Bangalore
...           ...      ...            ...                  ...        ...
9995   E-commerce  2365631             No                  NaN     Jaipur
9996   Automotive  1588370             No                  NaN  Hyderabad
9997    Logistics  1086626             No                  NaN      Delhi
9998   Automotive  1117160             No                  NaN    Kolkata
9999          NaN        0             No                  NaN       Pune

[10000 rows x 15 columns]

In [3]:
df.head()

,Student ID,Name,Gender,Year,Skills,Backlogs,Projects Completed,Internships,Companies Placed,Company Type,Domain,Salary,Higher Studies,Higher Studies Field,Location
0,1,Aryan Ghosal,Male,2023,"Digital Marketing, ML/AI, Blockchain",1,6,2,TCS,Established,Automotive,2271743,No,NaN,Ahmedabad
1,2,Kunal Pillai,Male,2023,"Blockchain, Python, Networking",0,10,2,Meta,Established,E-commerce,1386191,No,NaN,Delhi
2,3,Dev Gupta,Male,2023,C++,1,5,0,NaN,NaN,NaN,0,No,NaN,Kolkata
3,4,Manish Yadav,Male,2023,"DevOps, Networking",1,8,4,Zomato,Startup,FinTech,1011924,No,NaN,Chennai
4,5,Isha Singh,Female,2023,"Web Dev (Full Stack), ML/AI, DevOps",0,8,3,Tata Motors,Established,IT Services,1017889,No,NaN,Bangalore

In [4]:
df.drop(columns=["Name"],inplace= True)

df.columns

In [6]:
df.columns

Index(['Student ID', 'Gender', 'Year', 'Skills', 'Backlogs',
       'Projects Completed', 'Internships', 'Companies Placed', 'Company Type',
       'Domain', 'Salary', 'Higher Studies', 'Higher Studies Field',
       'Location'],
      dtype='object')

In [7]:
# finding missing values in our data 

df.isnull().sum()

Student ID                 0
Gender                     0
Year                       0
Skills                     0
Backlogs                   0
Projects Completed         0
Internships                0
Companies Placed        2201
Company Type            2201
Domain                  2201
Salary                     0
Higher Studies             0
Higher Studies Field    7673
Location                   0
dtype: int64

In [8]:
df["Companies Placed"].fillna("Not Placed", inplace=True)
df["Company Type"].fillna("Not Placed", inplace=True)
df["Domain"].fillna("Not Placed", inplace=True)

In [9]:
df.isnull().sum()

Student ID                 0
Gender                     0
Year                       0
Skills                     0
Backlogs                   0
Projects Completed         0
Internships                0
Companies Placed           0
Company Type               0
Domain                     0
Salary                     0
Higher Studies             0
Higher Studies Field    7673
Location                   0
dtype: int64

In [10]:
df["Higher Studies Field"].fillna("Not Applicable", inplace=True)

In [11]:
df.isnull().sum()

Student ID              0
Gender                  0
Year                    0
Skills                  0
Backlogs                0
Projects Completed      0
Internships             0
Companies Placed        0
Company Type            0
Domain                  0
Salary                  0
Higher Studies          0
Higher Studies Field    0
Location                0
dtype: int64

In [13]:
df.to_csv("placements_cleaned.csv", index=False)

In [14]:
pd.read_csv("placements_cleaned.csv").head()

,Student ID,Gender,Year,Skills,Backlogs,Projects Completed,Internships,Companies Placed,Company Type,Domain,Salary,Higher Studies,Higher Studies Field,Location
0,1,Male,2023,"Digital Marketing, ML/AI, Blockchain",1,6,2,TCS,Established,Automotive,2271743,No,Not Applicable,Ahmedabad
1,2,Male,2023,"Blockchain, Python, Networking",0,10,2,Meta,Established,E-commerce,1386191,No,Not Applicable,Delhi
2,3,Male,2023,C++,1,5,0,Not Placed,Not Placed,Not Placed,0,No,Not Applicable,Kolkata
3,4,Male,2023,"DevOps, Networking",1,8,4,Zomato,Startup,FinTech,1011924,No,Not Applicable,Chennai
4,5,Female,2023,"Web Dev (Full Stack), ML/AI, DevOps",0,8,3,Tata Motors,Established,IT Services,1017889,No,Not Applicable,Bangalore